# Generated by Django 4.2.3 on 2023-07-14 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
