apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: "webeventspython"
  POSTGRES_USER: "eventadmin"
  POSTGRES_PASSWORD: "secret1234#"
  HOST: "postgresdb.default"
  PORT: "5432"