apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  
  name: db-persistent-pvc2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  
  resources:
    requests:
      # the PVC storage
      storage: 8Gi

  